language: php

sudo: false

matrix:
  allow_failures:
    - php: hhvm
  include:
    - php: 5.4
      env: WP_VERSION=4.6
      dist: precise

before_script:
  - composer self-update --no-interaction
  - composer install --no-interaction

script:
  - vendor/bin/phpcs
